### ISSUE TITLE
Getting Error Code : 8192 (Represents an error message from the server)

### ISSUE THREAD

**Issue by iflairBhavin** [strongloop/loopback-connector-cassandra#1]
Respected Sir,

I am using strongloop with data source CASSANDRA. The test connection is success. I can try to add one new row in the DB but getting error code 8192 as a response from server. See attached screenshot for your reference. 

Can you please help?. Thanks in advance for your help.

![loopback-connector-cassandra-error](https://cloud.githubusercontent.com/assets/16224364/12672895/6fa2675c-c69f-11e5-8b1f-a8729131cfd8.png)

Thanks,
Bhavin Bhalodia.

**Comment by jorgedangelo** [comment]
hello, i need a loopback connector for cassandra. is posible?

**Comment by Setogit** [comment]
cassandra connector v1 published to npm  closing. @iflairBhavin  @jorgedangelo
