### ISSUE TITLE
pagination support

### ISSUE THREAD

**Issue by Setogit** [strongloop/loopback-connector-cassandra#13]
design question: do we expose the TOKEN to the C* connector API, or can we completely hide in under the hood and support pagination?

**Comment by anshulrvce** [comment]
For pagination support cassandra driver has eachRow function, which is not exposed in the loopback connector.
why is it not exposed in cassandra connector?
let us know any ETA for this.

**Comment by AlexDM0** [comment]
We would also be greatly interested in pagination support. Is there any news on this?

**Comment by abegau** [comment]
Same here, greatly interested in pagination support.

**Comment by george-oakling** [comment]
Same here :) I can help with particular updates.
