### ISSUE TITLE
unable to create save basic user in cassandra

### ISSUE THREAD

**Issue by motleycrew** [strongloop/loopback-connector-cassandra#26]
I am unable to save basic user for authentication loopback 3. 
form.js:128:32)',
  message: 'IN predicates on non-primary-key columns (property) is not yet supported',
  info: 'Represents an error message from the server',
  code: 8704,
  coordinator: 'localhost:9042',
  query: 'SELECT "model","property","accessType","permission","principalType","principalId","id" FROM "ACL" WHERE "model"=? AND "property" IN (?,?) AND "accessType" IN (?,?) ALLOW FILTERING' }
Unhandled error for request POST /RMUser: Error: IN predicates on non-primary-key columns (property) is not yet supported. 

Model config below.

 "User": {
    "dataSource": "db",
    "public": false
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "cassandra",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "cassandra",
    "public": false
  },
  "Role": {
    "dataSource": "cassandra",
    "public": false
  },
  "RMUser": {
    "dataSource": "cassandra",
    "public": true,
    "options": {
      "emailVerificationRequired": true
    }
  }

I used automigrate to create tables. It created table like this. Which is incorrect for the query below

CREATE TABLE nfeeds."ACL" (
    id uuid PRIMARY KEY,
    "accessType" text,
    model text,
    permission text,
    "principalId" text,
    "principalType" text,
    property text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

**Comment by shalomsam** [comment]
+1

**Comment by belghithb** [comment]
+1
