### ISSUE TITLE
Datasource not available after installing loopback-connector-cassandra

### ISSUE THREAD

**Issue by luxigo** [strongloop/loopback-connector-cassandra#3]
We are wondering about the status of the project because the datasource is not available even after installing loopback-connector-cassandra with npm install &lt;local-directory&gt; (so it's not related to issue #2).

Also the link for the official documentation at http://docs.strongloop.com/display/LB/Cassandra+connector (from README.md) is dead and searching for "cassandra" in the strongloop documentation yields nothing.

Could you clarify the status of the project please ?

**Comment by belgacea** [comment]
+1

**Comment by masalinas** [comment]
Yes we would like to know the status of the project, is very important for us because we use strongloop and cassandra too.

**Comment by Setogit** [comment]
published to npm. closing. @luxigo, @belgacea , @masalinas
