### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by masalinas** [strongloop/loopback-connector-cassandra#4]
Whitch is the status of the project?. I tried install the package from npm and anything was download, and not exist any commit from many time.

I have and cassandra prjoect and would like to use loopback with this connector ...

**Comment by jorgedangelo** [comment]
massalinas (Miguel). Estimado, pudo solucionar su problema? No puedo encontrar por ningún ladi un conector para cassandra. existen?

**Comment by Setogit** [comment]
published to npm. closing. @masalinas
