### ISSUE TITLE
Error: unconfigured table 

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback-connector-cassandra#40]
I use cassandra 3.10
When I create record with loopback API, server show error Error: unconfigured table UserEvent
Check it please !

**Comment by manojchandrashekar** [comment]
You need to either manually create the table using cqlsh or use migrate before using the APIs.

**Comment by hoangtrongphuc** [comment]
Thank you, @manojchandrashekar .
Work like a charm !

**Comment by belghithb** [comment]
@manojchandrashekar 
hello, when i created tables manually it works but when i try to automigrate or autoupdate it didn't work , may you explain how to use migrate ?
thanks in advance!

**Comment by manojchandrashekar** [comment]
I'm sorry, I haven't tested it with migration - Maybe this will help? https://loopback.io/doc/ja/lb3/Creating-a-database-schema-from-models.html#auto-update

**Comment by belghithb** [comment]
thank you for your  response

2018-03-27 9:47 GMT+01:00 Manoj Chandrashekar <notifications@github.com>:
