### ISSUE TITLE
Support cassandra collections

### ISSUE THREAD

**Issue by shenghu** [strongloop/loopback-connector-cassandra#60]
# Description
- [x] Define model to use collections
- [x] Insert/update column of collection type
- [ ] Extended operation on collection type, e.g. updating an individual element of a Map
- [ ] Nested collections

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
PR #59 has landed.  Thanks for your contribution!

**Comment by shenghu** [comment]
@dhmlau I'm working on the 'Extended operation on collection type, e.g. updating an individual element of a Map'. For nested collection, I think it can be deferred.
