### ISSUE TITLE
Milliseconds are missing when save and retrieve date type from cassandra.

### ISSUE THREAD

**Issue by brianunlam** [strongloop/loopback-connector-cassandra#83]
# Description/Steps to reproduce
 Create a model which uses Date type. Try to save with milliseconds. Check inside Cassandra how the value was saved. It loses milliseconds.
Save manually a date in Cassandra using milliseconds. Retrieve it from loopback 4, you will see milliseconds are set to 0. 

The problem is inside cassandra.js
When you save the date it uses the function:

``` javascript
function dateToMysql(date) {
  return date.getUTCFullYear() + '-' +
    fillZeros(date.getUTCMonth() + 1) + '-' +
    fillZeros(date.getUTCDate()) + ' ' +
    fillZeros(date.getUTCHours()) + ':' +
    fillZeros(date.getUTCMinutes()) + ':' +
    fillZeros(date.getUTCSeconds());

  function fillZeros(v) {
    return parseInt(v) < 10 ? '0' + v : v;
  }
}
```
As you can see millisecons are not being taking into account.

This could be a possible solution:

``` javascript
function dateToMysql(date:Date) {
  function fillZeros(v, n = 2) {
    return ('0'.repeat(n-1) + v).slice(-n);
  }
  return date.getUTCFullYear() + '-' +
    fillZeros(date.getUTCMonth() + 1) + '-' +
    fillZeros(date.getUTCDate()) + ' ' +
    fillZeros(date.getUTCHours()) + ':' +
    fillZeros(date.getUTCMinutes()) + ':' +
    fillZeros(date.getUTCSeconds()) + '.' +
    fillZeros(date.getUTCMilliseconds(),3); 
}
```

When you retrieve a Date it uses function:

Cassandra.prototype.fromColumnValue
``` javascript 
case 'Date':

        // Cassandra allows, unless NO_ZERO_DATE is set, dummy date/time entries
        // new Date() will return Invalid Date for those, so we need to handle
        // those separate.
        if (val == '0000-00-00 00:00:00') {
          val = null;
        } else {
          val = new Date(val.toString().replace(/GMT.*$/, 'GMT'));
        }
````

val.toString() get rid of millisecons, val is actually a Date, you can return it without any conversion. Return val without any conversion solves the issue.

**Comment by raymondfeng** [comment]
@brianunlam Would you please contribute a patch?
